jobs:
  include:
    - os: linux
      language: java
      dist: trusty
      sudo: true
      jdk: openjdk11
    - os: windows
      language: shell

env:
  - MAVEN_VERSION=3.6.3

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
    choco install openjdk11 --version 11.0.5.10;
    export JAVA_HOME='/c/Program Files/OpenJDK/openjdk-11.0.5_10'
    export PATH="${PATH}:${JAVA_HOME}/bin";
    choco install maven --version ${MAVEN_VERSION};
    export PATH="${PATH}:/c/ProgramData/chocolatey/lib/maven/apache-maven-3.6.3/bin";
    fi;
  - "echo $PATH"
  - "export JAVA_OPTS=-Xmx512m"
  - "mvn -N io.takari:maven:0.7.7:wrapper -Dmaven=${MAVEN_VERSION}"
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi

# Default installation command is
# mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
# this is what we test as our build phase so skip it here.
install:
  - true

script:
  - mvn --settings .travis/settings.xml -Dgpg.skip  install -B -V

deploy:
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: fcrepo-exts/fcrepo-storage-ocfl
      branch: main
      condition: $TRAVIS_OS_NAME = linux
